# Generated by Django 4.0.6 on 2022-07-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_description_contact_desc_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
